/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqsRouteImport } from './routes/sqs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as S3RouteImport } from './routes/s3'
import { Route as LambdaRouteImport } from './routes/lambda'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'

const SqsRoute = SqsRouteImport.update({
  id: '/sqs',
  path: '/sqs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const S3Route = S3RouteImport.update({
  id: '/s3',
  path: '/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const LambdaRoute = LambdaRouteImport.update({
  id: '/lambda',
  path: '/lambda',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/graph': typeof GraphRoute
  '/lambda': typeof LambdaRoute
  '/s3': typeof S3Route
  '/settings': typeof SettingsRoute
  '/sqs': typeof SqsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/graph': typeof GraphRoute
  '/lambda': typeof LambdaRoute
  '/s3': typeof S3Route
  '/settings': typeof SettingsRoute
  '/sqs': typeof SqsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/graph': typeof GraphRoute
  '/lambda': typeof LambdaRoute
  '/s3': typeof S3Route
  '/settings': typeof SettingsRoute
  '/sqs': typeof SqsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/graph'
    | '/lambda'
    | '/s3'
    | '/settings'
    | '/sqs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/graph' | '/lambda' | '/s3' | '/settings' | '/sqs'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/graph'
    | '/lambda'
    | '/s3'
    | '/settings'
    | '/sqs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  GraphRoute: typeof GraphRoute
  LambdaRoute: typeof LambdaRoute
  S3Route: typeof S3Route
  SettingsRoute: typeof SettingsRoute
  SqsRoute: typeof SqsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sqs': {
      id: '/sqs'
      path: '/sqs'
      fullPath: '/sqs'
      preLoaderRoute: typeof SqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3': {
      id: '/s3'
      path: '/s3'
      fullPath: '/s3'
      preLoaderRoute: typeof S3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lambda': {
      id: '/lambda'
      path: '/lambda'
      fullPath: '/lambda'
      preLoaderRoute: typeof LambdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  GraphRoute: GraphRoute,
  LambdaRoute: LambdaRoute,
  S3Route: S3Route,
  SettingsRoute: SettingsRoute,
  SqsRoute: SqsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
