/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqsRouteImport } from './routes/sqs'
import { Route as IndexRouteImport } from './routes/index'

const SqsRoute = SqsRouteImport.update({
  id: '/sqs',
  path: '/sqs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sqs': typeof SqsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sqs': typeof SqsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sqs': typeof SqsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sqs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sqs'
  id: '__root__' | '/' | '/sqs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SqsRoute: typeof SqsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sqs': {
      id: '/sqs'
      path: '/sqs'
      fullPath: '/sqs'
      preLoaderRoute: typeof SqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SqsRoute: SqsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
